# Generated by Django 6.0.1 on 2026-02-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=30)),
                ('Contact', models.IntegerField()),
                ('Qualification', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
            ],
        ),
    ]
